// Maps common everyday phrasing and professional/clinical jargon to the words
// actually likely to appear in a resource's name, notes, or tags — so someone
// searching "rehab" and someone searching "residential treatment" find the
// same thing. Keys are matched as substrings of the (lowercased) query, so
// both single words and short phrases work.
export const SEARCH_SYNONYMS = {
  "rehab": ["substance-use treatment", "residential treatment", "treatment"],
  "rehabilitation": ["substance-use treatment", "residential treatment"],
  "detox": ["withdrawal management", "detoxification"],
  "suboxone": ["buprenorphine", "mat", "moud", "medication-assisted treatment"],
  "methadone": ["medication-assisted treatment", "mat"],
  "food stamps": ["snap", "dhs", "benefits"],
  "snap": ["food stamps", "benefits"],
  "wic": ["women infants children", "nutrition"],
  "felon": ["reentry", "justice-involved", "criminal record"],
  "felony": ["reentry", "justice-involved", "criminal record"],
  "ex-con": ["reentry", "justice-involved"],
  "ride": ["transportation", "bus", "transit"],
  "bus pass": ["transportation", "transit"],
  "glasses": ["vision", "optical", "eye care"],
  "eye doctor": ["vision", "optical"],
  "domestic abuse": ["domestic violence", "intimate partner violence"],
  "abuse": ["domestic violence", "sexual assault"],
  "place to sleep": ["shelter", "emergency housing", "homeless"],
  "homeless": ["shelter", "emergency housing", "housing"],
  "nowhere to go": ["shelter", "emergency housing"],
  "help with lights": ["utility assistance", "electric bill", "utilities"],
  "electric bill": ["utility assistance", "utilities"],
  "water bill": ["utility assistance", "utilities"],
  "counseling": ["mental health", "therapy", "counselor"],
  "therapy": ["mental health", "counseling"],
  "therapist": ["mental health", "counseling"],
  "sober living": ["recovery housing"],
  "dentist": ["dental care"],
  "dental": ["dentist"],
  "medicaid": ["insurance", "sooncare"],
  "sooncare": ["medicaid", "insurance"],
  "jail": ["reentry", "justice-involved", "incarceration"],
  "prison": ["reentry", "justice-involved", "incarceration"],
  "probation": ["reentry", "justice-involved"],
  "kids": ["youth", "children", "childcare"],
  "child care": ["childcare"],
  "daycare": ["childcare"],
  "elderly": ["senior"],
  "old people": ["senior", "elderly"],
  "gay": ["lgbtq"],
  "lesbian": ["lgbtq"],
  "trans": ["lgbtq"],
  "immigrant": ["immigration"],
  "refugee": ["immigration"],
  "veteran": ["veterans"],
  "military": ["veterans"],
  "pregnant": ["pregnancy", "maternal health"],
  "eviction": ["housing", "rent assistance"],
  "behind on rent": ["rent assistance", "housing"],
  "unemployed": ["employment", "job"],
  "job": ["employment"],
  "resume": ["employment", "job training"],
  "id card": ["id documents", "identification"],
  "birth certificate": ["id documents"],
  "drivers license": ["id documents"],
  "social security card": ["id documents"],
  "grief": ["loss support"],
  "death": ["grief", "loss support"],
  "tribal": ["native american"],
  "indian health": ["native american", "tribal"],
  "developmental disability": ["autism", "disability services"],
  "special needs": ["disability services", "autism"],
  "alcoholic": ["substance use", "aa", "alcoholics anonymous"],
  "drug addiction": ["substance use", "treatment"],
  "narcotics anonymous": ["substance use", "na"],
};
