// One-time seed data for a fresh Supabase project — see scripts/migrate-seed.mjs.
// Kept in its own module (not inlined in App.jsx) so the migration script can
// import it directly without pulling in any React/browser code.
export const SEED = [
  {
    id: "valliant-house", name: "Valliant House", category: "treatment",
    subcategory: "Residential (ASAM 3.5)", address: "Enid, OK", phone: "", website: "",
    populations: "Adult men", insurance: "Add what you accept here",
    notes: "Your facility — add full details.",
    issues: ["Substance use", "Mental health"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "northwest-center", name: "Northwest Center for Behavioral Health", category: "treatment",
    subcategory: "Outpatient, IOP, medication management", address: "702 N Grand Ave, Enid, OK 73701",
    phone: "580-234-3791", website: "",
    populations: "Adults",
    insurance: "Cash/self-pay, Medicaid, Medicare, private insurance, Tricare — verify current panel",
    notes: "Outpatient therapy, IOP, med management.",
    issues: ["Substance use", "Mental health"], barriers: ["Medicaid accepted", "Sliding scale"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "yfs-enid", name: "Youth & Family Services of North Central Oklahoma", category: "treatment",
    subcategory: "Outpatient substance use & family services", address: "605 W Oxford St, Enid, OK 73701",
    phone: "580-233-8300", website: "",
    populations: "Youth, adults, families; DUI/DWI, criminal-justice clients",
    insurance: "Verify current panel", notes: "",
    issues: ["Substance use", "Mental health"], barriers: ["Criminal record OK"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "care-for-change", name: "C.A.R.E. For Change, Inc.", category: "treatment",
    subcategory: "Free substance use treatment & trauma services", address: "Enid, OK",
    phone: "", website: "", populations: "Qualifying low-income individuals",
    insurance: "Free for those who qualify", notes: "Community-driven, sliding scale / free care.",
    issues: ["Substance use", "Mental health"], barriers: ["Free", "No insurance needed"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "maine-street-aa", name: "Maine Street AA Group", category: "support",
    subcategory: "AA — open & closed meetings, daily", address: "Enid, OK (verify exact address)",
    phone: "", website: "",
    populations: "Anyone seeking AA support", insurance: "N/A — free",
    notes: "Pulled from a public AA directory — please confirm exact address and current times, then check the verified box.",
    schedule: [
      { id: "s1", day: "Monday", time: "6:15–7:15am", label: "Discussion (Open)", frequency: "Weekly" },
      { id: "s2", day: "Monday", time: "12:00–1:00pm", label: "Big Book (Closed)", frequency: "Weekly" },
      { id: "s3", day: "Monday", time: "7:00–8:00pm", label: "Big Book (Closed)", frequency: "Weekly" },
      { id: "s4", day: "Tuesday", time: "12:00–1:00pm", label: "Discussion (Open)", frequency: "Weekly" },
      { id: "s5", day: "Tuesday", time: "7:00–8:00pm", label: "Discussion (Open)", frequency: "Weekly" },
      { id: "s6", day: "Wednesday", time: "12:00–1:00pm", label: "Discussion (Open)", frequency: "Weekly" },
      { id: "s7", day: "Wednesday", time: "7:00–8:00pm", label: "12&12 Step Meeting (Open)", frequency: "Weekly" },
      { id: "s8", day: "Wednesday", time: "9:00–10:00pm", label: "Candlelight Discussion (Open)", frequency: "Weekly" },
      { id: "s9", day: "Thursday", time: "12:00–1:00pm", label: "Discussion (Open)", frequency: "Weekly" },
      { id: "s10", day: "Thursday", time: "7:00–8:00pm", label: "Tradition Study (Closed)", frequency: "Weekly" },
      { id: "s11", day: "Friday", time: "12:00–1:00pm", label: "Discussion (Open)", frequency: "Weekly" },
      { id: "s12", day: "Friday", time: "7:00–8:00pm", label: "Discussion (Open)", frequency: "Weekly" },
      { id: "s13", day: "Saturday", time: "8:00–9:00am", label: "Meeting (verify type)", frequency: "Weekly" },
    ],
    issues: ["Substance use"], barriers: ["Free"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "tyler-house-group", name: "Tyler House Group", category: "support",
    subcategory: "AA — open & closed meetings, daily", address: "Tyler St, Enid, OK 73703 (verify exact address)",
    phone: "", website: "",
    populations: "Anyone seeking AA support; Wed 6:30pm is a women's meeting", insurance: "N/A — free",
    notes: "Pulled from a public AA directory — please confirm exact address and current times, then check the verified box.",
    schedule: [
      { id: "s1", day: "Monday", time: "12:00–1:00pm", label: "Meeting (Closed)", frequency: "Weekly" },
      { id: "s2", day: "Monday", time: "8:00–9:00pm", label: "Meeting (Open)", frequency: "Weekly" },
      { id: "s3", day: "Tuesday", time: "12:00–1:00pm", label: "Meeting (Closed)", frequency: "Weekly" },
      { id: "s4", day: "Tuesday", time: "8:00–9:00pm", label: "Meeting (Open)", frequency: "Weekly" },
      { id: "s5", day: "Wednesday", time: "12:00–1:00pm", label: "Meeting (Closed)", frequency: "Weekly" },
      { id: "s6", day: "Wednesday", time: "6:30–7:30pm", label: "Women's Meeting (Closed)", frequency: "Weekly" },
      { id: "s7", day: "Wednesday", time: "8:00–9:00pm", label: "Meeting (Open)", frequency: "Weekly" },
      { id: "s8", day: "Thursday", time: "12:00–1:00pm", label: "Meeting (Closed)", frequency: "Weekly" },
      { id: "s9", day: "Thursday", time: "8:00–9:00pm", label: "Meeting (Open)", frequency: "Weekly" },
      { id: "s10", day: "Friday", time: "12:00–1:00pm", label: "Meeting (Closed)", frequency: "Weekly" },
      { id: "s11", day: "Friday", time: "8:00–9:00pm", label: "Meeting (Open)", frequency: "Weekly" },
      { id: "s12", day: "Saturday", time: "12:00–1:00pm", label: "Meeting (Closed)", frequency: "Weekly" },
      { id: "s13", day: "Saturday", time: "8:00–9:00pm", label: "Meeting (Open)", frequency: "Weekly" },
      { id: "s14", day: "Sunday", time: "12:00–1:00pm", label: "Meeting (Closed)", frequency: "Weekly" },
      { id: "s15", day: "Sunday", time: "8:00–9:00pm", label: "Meeting (Open)", frequency: "Weekly" },
    ],
    issues: ["Substance use"], barriers: ["Free"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "na-clubhouse-enid", name: "NA Club House Group", category: "support",
    subcategory: "NA meeting", address: "924 E Oklahoma Ave, Enid, OK 73701", phone: "",
    website: "", populations: "Anyone seeking NA support", insurance: "N/A — free",
    notes: "Known meeting: \"Right Group\" — 6:00 PM (day/recurrence unconfirmed). Pulled from a public NA directory — please confirm day and current time, then mark verified.",
    issues: ["Substance use"], barriers: ["Free"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "okc-intergroup", name: "OKC Intergroup — Enid AA Meeting Finder", category: "support",
    subcategory: "Official, live-updating AA meeting list (backup source)", address: "Online directory",
    phone: "405-524-1100 (24hr hotline)", website: "https://okcintergroup.org/meetings/?tsml-region=enid",
    populations: "Anyone seeking AA meetings in Enid", insurance: "N/A — free",
    notes: "Use this to double-check or find meetings not yet added above — it updates live.",
    issues: ["Substance use"], barriers: ["Free", "24/7 availability"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "aa-oklahoma-area57", name: "AA Oklahoma Area 57 — Enid Meetings", category: "support",
    subcategory: "Official, live-updating AA meeting list (backup source)", address: "Online directory",
    phone: "", website: "https://aaoklahoma.org/meetings?tsml-region=enid",
    populations: "Anyone seeking AA meetings", insurance: "N/A — free",
    notes: "Second official source; cross-check against OKC Intergroup listing.",
    issues: ["Substance use"], barriers: ["Free"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "na-meetings", name: "NA Meeting Search (na.org)", category: "support",
    subcategory: "Official, live-updating NA meeting list (backup source)", address: "Online directory", phone: "",
    website: "https://www.na.org/meetingsearch/", populations: "Anyone seeking NA meetings",
    insurance: "N/A — free",
    notes: "Use this to double-check or find NA meetings not yet added above.",
    issues: ["Substance use"], barriers: ["Free"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "a-simple-way", name: "A Simple Way", category: "sober_living",
    subcategory: "Sober living — men", address: "Enid, OK", phone: "(580) 231-8050", website: "",
    populations: "Men", insurance: "N/A", notes: "Call for current bed availability and intake process.",
    issues: ["Substance use", "Housing / rent"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "redemption-glow", name: "Redemption (M) & GLOW (W) Sober Houses", category: "sober_living",
    subcategory: "Sober living — men (Redemption) & women (GLOW)", address: "Enid, OK", phone: "(580) 362-7511",
    website: "", populations: "Men (Redemption house) and women (GLOW house)", insurance: "N/A",
    notes: "Call for current bed availability and intake process.",
    issues: ["Substance use", "Housing / rent"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "oxford-houses-enid", name: "Oxford Houses", category: "sober_living",
    subcategory: "Democratically-run, self-supporting sober living network", address: "Multiple Enid locations",
    phone: "", website: "https://oxfordvacancies.com", populations: "Men's and women's houses (varies by house)",
    insurance: "N/A — residents pay rent/dues", notes: "Check oxfordvacancies.com for current openings by house.",
    issues: ["Substance use", "Housing / rent"], barriers: [],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "hope-outreach-housing", name: "Hope Outreach Transitional Housing", category: "sober_living",
    subcategory: "Transitional housing — men, 2 houses", address: "Enid, OK", phone: "(580) 366-9422",
    website: "", populations: "Men", insurance: "N/A", notes: "Call for current bed availability and intake process.",
    issues: ["Substance use", "Housing / rent"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "serenity-house-sl", name: "Serenity House", category: "sober_living",
    subcategory: "Sober living — men", address: "Enid, OK", phone: "(539) 664-2370", website: "",
    populations: "Men", insurance: "N/A", notes: "Call for current bed availability and intake process.",
    issues: ["Substance use", "Housing / rent"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "gratitude-house", name: "Gratitude House", category: "sober_living",
    subcategory: "Sober living — men", address: "Enid, OK", phone: "(747) 346-2676",
    website: "", populations: "Men", insurance: "N/A", notes: "Contact: Anthony. Call for current bed availability and intake process.",
    issues: ["Substance use", "Housing / rent"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "salvation-army-enid", name: "The Salvation Army — Enid", category: "housing",
    subcategory: "Shelter, food pantry, utility/rent help, seasonal assistance", address: "Enid, OK",
    phone: "", website: "https://southernusa.salvationarmy.org/enid",
    populations: "General public, families", insurance: "N/A — free/donation-based",
    notes: "Client-choice food pantry, nightly meals, shelter, seasonal assistance.",
    issues: ["Housing / rent", "Food", "Clothing", "Utilities"], barriers: ["Free", "Walk-ins welcome"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "cdsa", name: "Community Development Support Association (CDSA)", category: "housing",
    subcategory: "Emergency assistance: rent, utilities, food referrals",
    address: "114 S Independence, Enid, OK 73701", phone: "580-242-6131", website: "",
    populations: "General public", insurance: "N/A", notes: "",
    issues: ["Housing / rent", "Utilities", "Food"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "enid-sos", name: "Enid Street Outreach Services (SOS)", category: "housing",
    subcategory: "Showers, laundry, clothing, mail, food pantry, advocacy",
    address: "112 S Jackson St, Enid, OK", phone: "", website: "https://enidsos.org",
    populations: "Low-income, unsheltered", insurance: "N/A — free",
    notes: "Open Tue/Wed/Thu.",
    issues: ["Clothing", "Food", "Housing / rent"], barriers: ["Free", "Walk-ins welcome", "No ID required"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "shepherds-cupboard", name: "Shepherd's Cupboard", category: "housing",
    subcategory: "Food pantry", address: "616 W Randolph, Enid, OK 73701", phone: "",
    website: "", populations: "General public", insurance: "N/A — free",
    notes: "Verify current hours.",
    schedule: [{ id: "s1", day: "Wednesday", time: "9:00–11:00am", label: "Food pantry", frequency: "1st & 2nd Wed of month" }],
    issues: ["Food"], barriers: ["Free"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "forgotten-ministries", name: "Forgotten Ministries / Food Outreach", category: "housing",
    subcategory: "Free lunches & groceries", address: "1714 S 4th St, Enid, OK 73701",
    phone: "580-616-3368", website: "", populations: "General public", insurance: "N/A — free",
    notes: "Verify current hours.",
    schedule: [{ id: "s1", day: "Saturday", time: "11:00am–1:00pm", label: "Free lunch & groceries", frequency: "1st Sat of month" }],
    issues: ["Food"], barriers: ["Free"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "welcome-table-fcc", name: "The Welcome Table (First Christian Church)", category: "housing",
    subcategory: "Free Sunday breakfast", address: "Enid, OK (confirm exact address)", phone: "",
    website: "", populations: "Anyone; has grown from ~70–100 to 180+ people weekly",
    insurance: "N/A — free",
    notes: "Started 2022 after Beacon stopped weekend meals. Confirm exact address/time, then check verified.",
    schedule: [{ id: "s1", day: "Sunday", time: "Morning (confirm exact time)", label: "Free breakfast", frequency: "Weekly" }],
    issues: ["Food"], barriers: ["Free", "Walk-ins welcome"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "enid-welcome-table", name: "Enid Welcome Table (Central Christian Church)", category: "housing",
    subcategory: "Free Sunday dinner — different name, different church than First Christian's breakfast above",
    address: "1111 W Broadway, Enid, OK", phone: "580-233-1214",
    website: "https://www.facebook.com/enidwelcometable/", populations: "Anyone; ~90–110 meals served weekly",
    insurance: "N/A — free",
    notes: "Restaurant-style meal, different host group cooks each week. Confirm current time (previously reported around 4:30–5:30pm) — verify before relying.",
    schedule: [{ id: "s1", day: "Sunday", time: "Evening, ~4:30–5:30pm (verify)", label: "Free dinner", frequency: "Weekly" }],
    issues: ["Food"], barriers: ["Free", "Walk-ins welcome"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "our-daily-bread", name: "Our Daily Bread", category: "housing",
    subcategory: "Free dine-in meals, meal delivery, prescription assistance",
    address: "616 W Randolph Ave, Enid, OK 73701", phone: "580-242-5718",
    website: "https://ourdailybreadenid.org",
    populations: "Anyone hungry — no questions asked; meal delivery for qualifying elderly/disabled; prescription assistance for unhoused patrons",
    insurance: "N/A — free (donations welcome)",
    notes: "Open Mon–Fri 7am–noon. Breakfast 7–9am, lunch 10:30am–noon. Take-out meals $3 if not dining in.",
    schedule: [
      { id: "s1", day: "Monday", time: "7:00am–12:00pm", label: "Free meals (breakfast 7–9am, lunch 10:30–12)", frequency: "Weekly" },
      { id: "s2", day: "Tuesday", time: "7:00am–12:00pm", label: "Free meals (breakfast 7–9am, lunch 10:30–12)", frequency: "Weekly" },
      { id: "s3", day: "Wednesday", time: "7:00am–12:00pm", label: "Free meals (breakfast 7–9am, lunch 10:30–12)", frequency: "Weekly" },
      { id: "s4", day: "Thursday", time: "7:00am–12:00pm", label: "Free meals (breakfast 7–9am, lunch 10:30–12)", frequency: "Weekly" },
      { id: "s5", day: "Friday", time: "7:00am–12:00pm", label: "Free meals (breakfast 7–9am, lunch 10:30–12)", frequency: "Weekly" },
    ],
    issues: ["Food"], barriers: ["Free", "Walk-ins welcome"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "loaves-and-fishes", name: "Loaves & Fishes", category: "housing",
    subcategory: "Food pantry", address: "701 E. Maine Ave, Enid, OK 73701", phone: "580-540-9830",
    website: "", populations: "General public", insurance: "N/A — free",
    notes: "Verify current hours.",
    schedule: [
      { id: "s1", day: "Monday", time: "1:00–4:00pm", label: "Food pantry", frequency: "Weekly" },
      { id: "s2", day: "Tuesday", time: "2:30–5:30pm", label: "Food pantry", frequency: "Weekly" },
      { id: "s3", day: "Wednesday", time: "1:00–4:00pm", label: "Food pantry", frequency: "Weekly" },
      { id: "s4", day: "Thursday", time: "9:00am–12:00pm", label: "Food pantry", frequency: "Weekly" },
    ],
    issues: ["Food"], barriers: ["Free"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "tri-county-family-resource", name: "Tri-County Family Resource Center", category: "housing",
    subcategory: "Family resource & referral center (details needed)", address: "Enid, OK",
    phone: "", website: "https://www.facebook.com/p/Tri-County-Family-Resource-Center-61565549545239/",
    populations: "", insurance: "",
    notes: "Confirmed to exist via its Facebook page, but address, phone, and full services aren't public yet — fill in what you know and add issue/barrier tags once confirmed.",
    issues: [], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "ywca-enid", name: "YWCA Enid — Crisis Center", category: "crisis",
    subcategory: "DV / sexual assault shelter, forensic exams, court advocacy, onsite legal aid",
    address: "525 S. Quincy, Enid, OK 73701", phone: "580-234-7581",
    website: "https://www.ywcaenid.com", populations: "Survivors of domestic violence, sexual assault, stalking, and their children",
    insurance: "N/A — free, confidential",
    notes: "24-hour hotline: 800-966-7644. Only AG-certified DV/SA provider in Garfield County. Confidential shelter location.",
    issues: ["Domestic violence", "Sexual assault", "Housing / rent", "Legal / court", "Crisis / emergency"],
    barriers: ["Free", "Confidential location", "24/7 availability"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "legal-aid-ok-enid", name: "Legal Aid Services of Oklahoma — Enid Office", category: "legal",
    subcategory: "Free civil legal help: DV, custody, divorce, immigration",
    address: "302 N. Independence St, Suite 402, Enid, OK 73701", phone: "800-256-9601",
    website: "https://legalaidok.org/", populations: "Low-income individuals",
    insurance: "Free", notes: "Intake line: 888-534-5243 or 918-428-4357. Interpretation available for non-English speakers.",
    issues: ["Legal / court", "Domestic violence", "ID & documents"],
    barriers: ["Free", "Interpreter available"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "okdhs-enid", name: "Oklahoma Human Services (DHS) — Enid Office", category: "employment",
    subcategory: "SNAP, TANF, SoonerCare/Medicaid applications, child welfare",
    address: "119 East Broadway Ave, Enid, OK 73701", phone: "",
    website: "https://oklahoma.gov/okdhs.html", populations: "General public meeting income guidelines",
    insurance: "N/A", notes: "Walk-ins accepted, appointments preferred. Bring photo ID, SS cards, proof of residence.",
    issues: ["Government benefits", "ID & documents"], barriers: ["Walk-ins welcome"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "enid-workforce", name: "Enid American Job Center (Workforce)", category: "employment",
    subcategory: "Job search, training, resume help", address: "114 S Independence, Enid, OK 73701",
    phone: "580-234-6043", website: "https://wowdb.org/resources/american-job-centers/",
    populations: "Job seekers", insurance: "N/A — free",
    notes: "WIOA Title I services.", issues: ["Employment"], barriers: ["Free", "Walk-ins welcome"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "garfield-county-health", name: "Garfield County Health Department", category: "medical",
    subcategory: "Public health services, immunizations, WIC", address: "2501 Mercer Dr, Enid, OK 73701",
    phone: "580-233-0650", website: "", populations: "General public",
    insurance: "Sliding scale for many services — verify", notes: "",
    issues: ["Medical care"], barriers: ["Sliding scale"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "integris-bass", name: "INTEGRIS Health Enid (Bass Baptist)", category: "medical",
    subcategory: "Hospital, ER, behavioral health (Meadowlake)", address: "600 S Monroe St, Enid, OK 73701",
    phone: "", website: "", populations: "General public",
    insurance: "Verify current panel", notes: "Includes INTEGRIS Bass Behavioral Health / Meadowlake campus.",
    issues: ["Medical care", "Mental health", "Crisis / emergency"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "st-marys-enid", name: "St. Mary's Regional Medical Center", category: "medical",
    subcategory: "Hospital, ER", address: "305 S 5th St, Enid, OK 73701", phone: "",
    website: "http://www.stmarysregional.com", populations: "General public",
    insurance: "Verify current panel", notes: "",
    issues: ["Medical care", "Crisis / emergency"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "988", name: "988 Suicide & Crisis Lifeline", category: "crisis",
    subcategory: "Call or text 988", address: "National (answered locally)", phone: "988",
    website: "https://988lifeline.org", populations: "Anyone in crisis",
    insurance: "N/A — free", notes: "24/7. Call or text.",
    issues: ["Crisis / emergency", "Mental health"], barriers: ["Free", "24/7 availability"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "211-oklahoma", name: "211 Oklahoma", category: "housing",
    subcategory: "General resource & referral hotline", address: "Statewide", phone: "211",
    website: "https://www.211oklahoma.org", populations: "Anyone", insurance: "N/A — free",
    notes: "Housing, food, transportation, employment, healthcare & mental health/SUD referrals in one call.",
    issues: ["Housing / rent", "Food", "Transportation", "Government benefits", "Crisis / emergency"],
    barriers: ["Free", "24/7 availability"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "enid-public-library", name: "Public Library of Enid & Garfield County", category: "youth_community",
    subcategory: "Library — teen programs, summer reading, free resources for all ages",
    address: "120 W Maine Ave, Enid, OK 73701", phone: "580-234-6313",
    website: "https://enid.okpls.org", populations: "All ages; teen/tween programs for ages 9+",
    insurance: "N/A — free with library card",
    notes: "Summer Reading Program runs June–July. Free WiFi, computers, homework help, ESL & job-skills programs. Largest library in NW Oklahoma.",
    schedule: [{ id: "s1", day: "Thursday", time: "4:30pm", label: "Teen Dungeons & Dragons (grades 6–12, drop-in)", frequency: "Weekly" }],
    issues: ["Youth activities", "Teen programs", "Summer / seasonal programs", "Employment"],
    barriers: ["Free", "Walk-ins welcome"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "gaslight-theatre", name: "Gaslight Theatre", category: "youth_community",
    subcategory: "Community theater — Gaslight Teens, Kids' Drama Camp, Turpin Little Theatre, Autry Theatre Classes",
    address: "221 N Independence St, Enid, OK 73701", phone: "580-234-2307",
    website: "https://www.gaslighttheatre.org", populations: "Kids, teens, and adults — separate programs by age",
    insurance: "N/A — program fees and ticket prices apply (verify current rates)",
    notes: "Kids' Drama Summer Camp runs in summer. Gaslight Teens puts on its own annual show. Free Shakespeare in the Park is Gaslight's only free program — confirm current schedule.",
    issues: ["Youth activities", "Teen programs", "Summer / seasonal programs"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "we-rock-the-spectrum-enid", name: "We Rock the Spectrum Kid's Gym — Enid", category: "youth_community",
    subcategory: "Sensory-friendly indoor gym for kids of all abilities, including autism",
    address: "3825 W Owen K Garriott Rd, Enid, OK 73703", phone: "580-478-6233",
    website: "https://werockthespectrumenid.com", populations: "Children of all abilities, including autism and other special needs",
    insurance: "N/A — paid open-play/membership; verify if any state-funded or scholarship options are currently offered",
    notes: "Sensory-safe equipment: swings, trampoline, crash mats, climbing structure. Runs summer camp weeks. Call ahead — hours vary with private rentals.",
    issues: ["Autism / developmental disability", "Youth activities", "Summer / seasonal programs"], barriers: [],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "sooner-success-garfield", name: "Sooner SUCCESS — Garfield County", category: "youth_community",
    subcategory: "Resource & referral coordination for families raising a child with special needs (birth–21)",
    address: "Garfield County, OK", phone: "580-366-9606",
    website: "https://soonersuccess.ouhsc.edu", populations: "Families of children/youth with special needs, birth to age 21",
    insurance: "N/A — free coordination service",
    notes: "OU Health Sciences program. Local coordinator connects families to diagnosis/screening, early intervention, education, financial assistance, and disability-specific resources — a strong first call for autism-related questions.",
    issues: ["Autism / developmental disability", "Youth activities", "Government benefits"],
    barriers: ["Free"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "denny-price-ymca", name: "Denny Price Family YMCA", category: "youth_community",
    subcategory: "Youth center, afterschool program, youth swim lessons, summer camp",
    address: "415 W Cherokee Ave, Enid, OK 73701", phone: "",
    website: "https://enidymca.org", populations: "All ages; strong youth/teen programming",
    insurance: "N/A — membership/program fees apply; ask about financial assistance (verify current policy)",
    notes: "Aquatics center, fitness center, youth center, afterschool childcare, youth swim programs.",
    issues: ["Youth activities", "Teen programs", "Summer / seasonal programs"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "enid-parks-rec", name: "Enid Parks & Recreation", category: "youth_community",
    subcategory: "City parks, splash pads, seasonal & summer programs", address: "401 W Owen K Garriott Rd, Enid, OK 73701",
    phone: "", website: "https://www.enid.org/Services/Parks-Recreation",
    populations: "General public, families", insurance: "N/A — parks free; some programs have fees",
    notes: "30+ parks and 400+ acres citywide. Check the city site for current splash pad schedules and seasonal program sign-ups.",
    issues: ["Youth activities", "Summer / seasonal programs"], barriers: ["Free", "Walk-ins welcome"],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "bennies-barn", name: "Bennie's Barn", category: "youth_community",
    subcategory: "Equine (horse) therapy — Therapeutic Riding, Step-Up Academy, Sensory Trail, Horses for Heroes",
    address: "4914 East Rupe, Enid, OK 73701", phone: "580-548-7258",
    website: "https://www.benniesbarn.org",
    populations: "Individuals with physical, cognitive, social, or emotional needs; veterans with PTSD/combat trauma (Horses for Heroes)",
    insurance: "N/A — nonprofit; verify current program costs and scholarship availability",
    notes: "PATH-certified instructors. Sensory Trail has 12+ stations for sensory development. Riders apply via the Rider Application on their site. Also does sleigh rides seasonally.",
    issues: ["Autism / developmental disability", "Mental health", "Youth activities", "Veterans services"],
    barriers: [],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "enid-va-clinic", name: "Enid VA Clinic", category: "medical",
    subcategory: "Veterans primary care, mental health, specialty care", address: "915 E Owen K Garriott Rd, Enid, OK 73701",
    phone: "580-977-1855", website: "https://www.va.gov/oklahoma-city-health-care/locations/enid-va-clinic/",
    populations: "Veterans enrolled in VA health care", insurance: "VA health benefits",
    notes: "Mon–Fri 8am–4:30pm. In-person mental health appointments (individual & group therapy). Works with DAV for appointment transportation.",
    issues: ["Medical care", "Mental health", "Veterans services"], barriers: [],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "dav-chapter-66", name: "Disabled American Veterans (DAV) — Chapter 66 Enid", category: "employment",
    subcategory: "Free VA claims & benefits assistance for veterans and dependents",
    address: "202 West Walnut, Enid, OK", phone: "580-242-3808", website: "",
    populations: "Veterans and their dependents — membership not required",
    insurance: "N/A — free service",
    notes: "Open Mon–Wed 10am–3pm and by appointment. Accredited service officers help file and appeal VA claims.",
    issues: ["Veterans services", "Government benefits"], barriers: ["Free"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "ecdc", name: "Enid Counseling & Diagnostic Center (ECDC)", category: "treatment",
    subcategory: "Psychological assessment/diagnostic testing + individual, family & group counseling",
    address: "230 W Maple Ave, Enid, OK 73701", phone: "580-242-5544",
    website: "https://www.ecdcweb.com",
    populations: "Children (testing ages 4+), adolescents, adults, families",
    insurance: "Accepts most insurance incl. Medicaid, Medicare, Tricare. Sliding fee scale — serves regardless of ability to pay.",
    notes: "CARF accredited. Multidisciplinary staff: clinical psychologists, LPCs, drug/alcohol counselors. Diagnostic testing for ADHD, learning disabilities, autism, cognitive/personality/neuropsych, sensory processing. Also offers PCIT, Equine Assisted Psychotherapy, and Christian counseling option. Group therapy available.",
    issues: ["Mental health", "Autism / developmental disability", "Substance use"],
    barriers: ["Medicaid accepted", "Sliding scale"],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "alpha-assessment-counseling", name: "Alpha Assessment & Counseling, LLC", category: "treatment",
    subcategory: "Private practice — individual, couples, youth counseling; anger management; guidance counseling",
    address: "409 E Cherokee Ave, Enid, OK 73701", phone: "580-234-8865",
    website: "https://alphaenid.com", populations: "Children, adolescents, adults, families",
    insurance: "Verify current panel", notes: "",
    issues: ["Mental health"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "wright-counseling-solutions", name: "Wright Counseling Solutions, PLLC", category: "treatment",
    subcategory: "Private practice — individual therapy, drug/alcohol assessments (ADSAC/SAP)",
    address: "300 W Cherokee Ave, Suite 102, Enid, OK 73701", phone: "580-340-7235",
    website: "", populations: "Adults", insurance: "Verify current panel",
    notes: "Includes LPC/LADC-licensed provider offering court-required ADSAC and SAP substance assessments alongside general therapy.",
    issues: ["Mental health", "Substance use", "Legal / court"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "selby-counseling-solutions", name: "Selby Counseling Solutions", category: "treatment",
    subcategory: "Private practice — EMDR, trauma, anxiety, depression", address: "516 W Broadway Ave, Enid, OK 73701",
    phone: "580-233-8900", website: "", populations: "Adults",
    insurance: "Accepts most insurances including Tricare; also cash, check, card, Cash App",
    notes: "LPC-Supervisor, Certified Clinical Trauma Professional. By appointment.",
    issues: ["Mental health"], barriers: [],
    connections: [], verifiedDate: "2026-07-21", status: "active", editedBy: "seed data", editedDate: null,
  },
  {
    id: "peace-of-mind-wellness", name: "Peace of Mind & Wellness Counseling", category: "treatment",
    subcategory: "Private practice — multiple LPCs & LCSW, individualized treatment",
    address: "Harding St, Suite A, Enid, OK 73703 (confirm exact address)", phone: "580-231-6153",
    website: "", populations: "Individuals with mental/behavioral health needs",
    insurance: "Cash, check, debit/credit card", notes: "Mon–Fri 9:30am–5:30pm. CBT, play therapy, reality/choice, solution-focused, family systems approaches.",
    issues: ["Mental health"], barriers: [],
    connections: [], verifiedDate: null, status: "active", editedBy: "seed data", editedDate: null,
  },
];
