export const S = {
  app: { fontFamily: "'Iowan Old Style', 'Georgia', serif", background: "#faf9f6", minHeight: "100vh", color: "#2f3437" },
  srOnly: { position: "absolute", width: 1, height: 1, padding: 0, margin: -1, overflow: "hidden", clip: "rect(0,0,0,0)", whiteSpace: "nowrap", border: 0 },
  loadingWrap: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "100vh", background: "#faf9f6" },
  loadingSpin: { width: 28, height: 28, border: "3px solid #e4e2dc", borderTopColor: "#2f6f5e", borderRadius: "50%", animation: "spin 0.8s linear infinite" },
  header: { borderBottom: "1px solid #e9e7e1", padding: "20px 0 0", background: "#fff" },
  headerContent: { maxWidth: 1000, margin: "0 auto", padding: "0 20px" },
  headerInner: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 14 },
  eyebrow: { fontFamily: "'Helvetica Neue', Arial, sans-serif", fontSize: 11, letterSpacing: 1, color: "#a8632a", fontWeight: 700, marginBottom: 4 },
  h1: { fontSize: 20, margin: 0, lineHeight: 1.3, fontWeight: 600 },
  clientSubhead: { fontSize: 13.5, color: "#6b7178", marginTop: 4, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  quickNeedGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))", gap: 8, marginBottom: 16 },
  quickNeedBtn: { display: "flex", alignItems: "center", textAlign: "left", border: "1.5px solid #e4e2dc", background: "#fff", borderRadius: 10, padding: "12px 14px", fontSize: 14, fontWeight: 600, color: "#2f3437", fontFamily: "'Helvetica Neue', Arial, sans-serif", lineHeight: 1.3 },
  addBtn: { display: "flex", alignItems: "center", gap: 6, background: "#2f6f5e", color: "#fff", border: "none", borderRadius: 8, padding: "9px 14px", fontSize: 13, fontFamily: "'Helvetica Neue', Arial, sans-serif", fontWeight: 600, flexShrink: 0 },
  utilityRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  segmentGroup: { display: "flex", background: "#f2f0ea", borderRadius: 8, padding: 3, gap: 2 },
  segmentBtn: { display: "flex", alignItems: "center", gap: 4, border: "none", background: "transparent", color: "#666c73", fontSize: 12, fontWeight: 600, padding: "6px 10px", borderRadius: 6 },
  segmentBtnActive: { background: "#fff", color: "#2f3437", boxShadow: "0 1px 2px rgba(0,0,0,0.08)" },
  utilBtn: { display: "flex", alignItems: "center", justifyContent: "center", minWidth: 32, height: 32, background: "#f2f0ea", border: "none", borderRadius: 8, color: "#5c6066", fontSize: 11, fontWeight: 700 },
  moreMenu: { position: "absolute", top: "calc(100% + 6px)", right: 0, background: "#fff", border: "1px solid #e4e2dc", borderRadius: 10, boxShadow: "0 4px 16px rgba(0,0,0,0.14)", padding: 6, zIndex: 20, display: "flex", flexDirection: "column", gap: 2, minWidth: 170 },
  moreMenuItem: { display: "flex", alignItems: "center", gap: 8, border: "none", background: "transparent", color: "#2f3437", fontSize: 13, fontWeight: 600, padding: "8px 10px", borderRadius: 6, textAlign: "left", fontFamily: "'Helvetica Neue', Arial, sans-serif", whiteSpace: "nowrap" },
  networkHint: { fontSize: 12, color: "#6b7178", fontFamily: "'Helvetica Neue', Arial, sans-serif", marginBottom: 10, lineHeight: 1.5 },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(47,52,55,0.4)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 50, padding: 16 },
  modalCard: { background: "#fff", borderRadius: 14, padding: 22, maxWidth: 440, width: "100%", maxHeight: "80vh", overflowY: "auto", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  insightsGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginBottom: 18 },
  insightStat: { background: "#faf9f6", borderRadius: 10, padding: "12px 10px" },
  insightNum: { fontSize: 22, fontWeight: 700, color: "#2f3437", fontFamily: "'Iowan Old Style', Georgia, serif" },
  insightLabel: { fontSize: 11, color: "#666c73", marginTop: 2, lineHeight: 1.3 },
  missRow: { display: "flex", justifyContent: "space-between", fontSize: 13, background: "#faf9f6", borderRadius: 6, padding: "6px 10px" },
  dayChip: { border: "1.5px solid #e4e2dc", background: "#fff", color: "#5c6066", borderRadius: 20, padding: "6px 14px", fontSize: 13, fontWeight: 700, fontFamily: "'Helvetica Neue', Arial, sans-serif", whiteSpace: "nowrap" },
  dayChipActive: { borderColor: "#a8632a", background: "#a8632a14", color: "#a8632a" },
  dayHeading: { padding: "14px 16px 4px", fontSize: 13, fontWeight: 700, color: "#6b7178", fontFamily: "'Helvetica Neue', Arial, sans-serif", letterSpacing: 0.4, textTransform: "uppercase" },
  occTime: { fontSize: 11.5, fontWeight: 700, color: "#a8632a", fontFamily: "'Helvetica Neue', Arial, sans-serif", marginBottom: 2 },
  scheduleDayRow: { marginBottom: 10 },
  scheduleDayName: { fontSize: 11.5, fontWeight: 700, color: "#a8632a", fontFamily: "'Helvetica Neue', Arial, sans-serif", textTransform: "uppercase", letterSpacing: 0.3, marginBottom: 3 },
  scheduleOcc: { fontSize: 13.5, color: "#3c4146", fontFamily: "'Helvetica Neue', Arial, sans-serif", lineHeight: 1.6 },
  scheduleEditRow: { display: "flex", alignItems: "center", gap: 8, background: "#fff", border: "1px solid #eceae4", borderRadius: 8, padding: "7px 10px", fontSize: 13, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  scheduleAddRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  searchRow: { display: "flex", gap: 8, marginBottom: 12 },
  searchBox: { display: "flex", alignItems: "center", gap: 8, background: "#f2f0ea", borderRadius: 10, padding: "10px 12px", flex: 1 },
  searchInput: { flex: 1, border: "none", background: "transparent", outline: "none", fontSize: 14, fontFamily: "'Helvetica Neue', Arial, sans-serif", color: "#2f3437" },
  clearBtn: { border: "none", background: "transparent", color: "#666c73", padding: 2 },
  filterToggle: { display: "flex", alignItems: "center", justifyContent: "center", gap: 6, position: "relative", padding: "0 14px", background: "#f2f0ea", border: "none", borderRadius: 10, color: "#5c6066", fontSize: 13, fontWeight: 600, fontFamily: "'Helvetica Neue', Arial, sans-serif", whiteSpace: "nowrap" },
  filterToggleActive: { background: "#2f6f5e14", color: "#2f6f5e" },
  filterBadge: { position: "absolute", top: -6, right: -6, background: "#a8632a", color: "#fff", fontSize: 10, fontWeight: 700, borderRadius: 10, minWidth: 16, height: 16, display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  quickReqRow: { display: "flex", flexWrap: "wrap", gap: 6, marginBottom: 12 },
  activeFilterSummary: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 6, marginBottom: 14 },
  activeFilterChip: { display: "flex", alignItems: "center", border: "1.5px solid #2f6f5e40", borderRadius: 20, overflow: "hidden", background: "#2f6f5e0d" },
  activeFilterChipLabel: { padding: "5px 4px 5px 10px", fontSize: 12, fontWeight: 600, color: "#2f6f5e", fontFamily: "'Helvetica Neue', Arial, sans-serif", whiteSpace: "nowrap" },
  activeFilterChipRemove: { border: "none", background: "transparent", padding: "5px 8px 5px 4px", color: "#2f6f5e99" },
  filterHint: { fontSize: 11.5, color: "#6b7178", fontFamily: "'Helvetica Neue', Arial, sans-serif", marginTop: 8 },
  chipRow: { display: "flex", gap: 8, overflowX: "auto", paddingBottom: 14, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  categoryRow: { display: "flex", flexWrap: "wrap", gap: 8, paddingBottom: 14, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  chip: { display: "flex", alignItems: "center", border: "1.5px solid", borderRadius: 20, padding: "6px 12px", fontSize: 12.5, fontWeight: 600, whiteSpace: "nowrap" },
  filterPanel: { background: "#f8f7f3", borderTop: "1px solid #eceae4", padding: "14px 0 16px", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  filterGroupLabel: { display: "flex", alignItems: "center", gap: 5, fontSize: 11, fontWeight: 700, color: "#6b7178", letterSpacing: 0.5, marginBottom: 8 },
  tagWrap: { display: "flex", flexWrap: "wrap", gap: 6 },
  tagGroupLabel: { fontSize: 10.5, fontWeight: 700, color: "#a8632a", letterSpacing: 0.4, textTransform: "uppercase", marginBottom: 5, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  tagChip: { border: "1.5px solid", borderRadius: 16, padding: "5px 10px", fontSize: 12, fontWeight: 500, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  clearFiltersBtn: { marginTop: 12, background: "transparent", border: "none", color: "#a8632a", fontSize: 12.5, fontWeight: 600, padding: 0, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  saveViewRow: { display: "flex", gap: 8, marginTop: 14, paddingTop: 12, borderTop: "1px solid #eceae4" },
  savedViewChip: { display: "flex", alignItems: "center", border: "1.5px solid #e4e2dc", borderRadius: 20, overflow: "hidden", background: "#fff" },
  savedViewBtn: { border: "none", background: "transparent", padding: "6px 4px 6px 12px", fontSize: 12.5, fontWeight: 600, color: "#a8632a", fontFamily: "'Helvetica Neue', Arial, sans-serif", whiteSpace: "nowrap" },
  savedViewRemove: { border: "none", background: "transparent", padding: "6px 10px 6px 4px", color: "#c2c6cc" },
  split: { display: "flex", maxWidth: 1000, margin: "0 auto" },
  listPane: { width: "38%", maxWidth: 360, borderRight: "1px solid #e9e7e1", maxHeight: "calc(100vh - 150px)", overflowY: "auto" },
  emptyState: { padding: 24, fontSize: 13.5, color: "#6b7178", fontFamily: "'Helvetica Neue', Arial, sans-serif", lineHeight: 1.5 },
  searchNotice: { padding: "10px 16px", fontSize: 12.5, color: "#a8632a", background: "#fbf1e6", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  listItem: { display: "flex", alignItems: "center", gap: 10, width: "100%", textAlign: "left", background: "transparent", border: "none", borderBottom: "1px solid #f0eee8", padding: "12px 16px", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  listItemMainBtn: { display: "flex", alignItems: "center", gap: 10, flex: 1, minWidth: 0, background: "transparent", border: "none", padding: 0, margin: 0, textAlign: "left", font: "inherit", color: "inherit", cursor: "pointer" },
  listItemActive: { background: "#f2f0ea" },
  listItemClient: { padding: "16px" },
  listItemMeta: { display: "flex", alignItems: "center", gap: 6, marginTop: 3, fontSize: 11.5, color: "#6b7178", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  costTag: { border: "1px solid #e4e2dc", borderRadius: 8, padding: "1px 6px", fontWeight: 600, color: "#5c6066" },
  verifDot: { width: 6, height: 6, borderRadius: "50%", flexShrink: 0 },
  listCallBtn: { display: "flex", alignItems: "center", justifyContent: "center", width: 40, height: 40, borderRadius: 8, background: "#2f6f5e14", color: "#2f6f5e", flexShrink: 0 },
  listIconWrap: { width: 32, height: 32, borderRadius: 8, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  listItemName: { fontSize: 14, fontWeight: 600, color: "#2f3437", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden", lineHeight: 1.3 },
  listItemSub: { fontSize: 12, color: "#6b7178", marginTop: 2, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  printDetails: { display: "none", fontSize: 11.5, color: "#3c4146", marginTop: 3, lineHeight: 1.5, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  detailPane: { flex: 1, minWidth: 0 },
  mobileBackBtn: { display: "none", alignItems: "center", gap: 4, border: "none", background: "transparent", color: "#a8632a", fontSize: 14, fontWeight: 600, fontFamily: "'Helvetica Neue', Arial, sans-serif", padding: "16px 16px 0" },
  placeholder: { display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", height: "60vh" },
  detailInner: { padding: "20px 22px 40px", maxWidth: 560 },
  detailTop: { display: "flex", gap: 12, marginBottom: 14 },
  detailIconWrap: { width: 42, height: 42, borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  detailName: { fontSize: 20, margin: "2px 0 2px", lineHeight: 1.25 },
  detailSubtitle: { fontSize: 13.5, color: "#666c73", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  warnBanner: { display: "flex", alignItems: "center", gap: 8, background: "#fbf1e6", color: "#a8632a", fontSize: 12.5, padding: "8px 12px", borderRadius: 8, marginBottom: 16, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  fieldGrid: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 6 },
  fieldRow: { display: "flex", gap: 8, padding: "8px 0" },
  fieldLabel: { fontSize: 11, color: "#6b7178", fontFamily: "'Helvetica Neue', Arial, sans-serif", textTransform: "uppercase", letterSpacing: 0.4 },
  fieldValue: { fontSize: 14, color: "#2f3437", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  infoBlock: { marginTop: 14, borderTop: "1px solid #f0eee8", paddingTop: 12 },
  meetingBlock: { marginTop: 14, borderTop: "1px solid #f0eee8", paddingTop: 12, background: "#faf6ee", margin: "14px -22px 0", padding: "12px 22px" },
  meetingText: { fontSize: 13.5, color: "#3c4146", lineHeight: 1.7, whiteSpace: "pre-line", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  infoBlockTitle: { display: "flex", alignItems: "center", gap: 6, fontSize: 11.5, fontWeight: 700, color: "#2f6f5e", fontFamily: "'Helvetica Neue', Arial, sans-serif", textTransform: "uppercase", letterSpacing: 0.4, marginBottom: 4 },
  infoBlockText: { fontSize: 14, color: "#3c4146", lineHeight: 1.5 },
  pillGroupLabel: { fontSize: 11, fontWeight: 700, color: "#6b7178", fontFamily: "'Helvetica Neue', Arial, sans-serif", letterSpacing: 0.4, marginBottom: 5, textTransform: "uppercase" },
  pillIssue: { display: "inline-block", background: "#2f6f5e14", color: "#2f6f5e", fontSize: 11.5, fontWeight: 600, borderRadius: 12, padding: "4px 9px", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  pillBarrier: { display: "inline-block", background: "#4a5a8a14", color: "#4a5a8a", fontSize: 11.5, fontWeight: 600, borderRadius: 12, padding: "4px 9px", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  sectionLabel: { fontSize: 11, fontWeight: 700, color: "#6b7178", fontFamily: "'Helvetica Neue', Arial, sans-serif", letterSpacing: 0.5, marginBottom: 8 },
  connRow: { display: "flex", alignItems: "center", gap: 10, width: "100%", background: "#fff", border: "1px solid #eceae4", borderRadius: 8, padding: "9px 12px", marginBottom: 6, fontFamily: "'Helvetica Neue', Arial, sans-serif", fontSize: 13.5 },
  connDot: { width: 8, height: 8, borderRadius: "50%", flexShrink: 0 },
  detailActions: { display: "flex", gap: 10, marginTop: 24, fontFamily: "'Helvetica Neue', Arial, sans-serif", flexWrap: "wrap" },
  clientActionRow: { display: "flex", gap: 10, marginBottom: 16 },
  clientCallBtn: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: "#2f6f5e", color: "#fff", textDecoration: "none", borderRadius: 10, padding: "14px 10px", fontSize: 15, fontWeight: 700, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  clientDirectionsBtn: { flex: 1, display: "flex", alignItems: "center", justifyContent: "center", gap: 8, background: "#2f3437", color: "#fff", textDecoration: "none", borderRadius: 10, padding: "14px 10px", fontSize: 15, fontWeight: 700, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  shareBtn: { display: "flex", alignItems: "center", gap: 6, background: "#fff", color: "#2f3437", border: "1px solid #e4e2dc", borderRadius: 8, padding: "9px 14px", fontSize: 13, fontWeight: 600 },
  attribution: { marginTop: 18, fontSize: 11.5, color: "#c2c6cc", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  closeBtn: { display: "flex", alignItems: "center", gap: 6, background: "#fff", color: "#a8632a", border: "1px solid #f0e2d0", borderRadius: 8, padding: "9px 14px", fontSize: 13, fontWeight: 600 },
  editBtn: { display: "flex", alignItems: "center", gap: 6, background: "#2f3437", color: "#fff", border: "none", borderRadius: 8, padding: "9px 14px", fontSize: 13, fontWeight: 600 },
  deleteBtn: { display: "flex", alignItems: "center", gap: 6, background: "#fff", color: "#b3413a", border: "1px solid #f0d8d5", borderRadius: 8, padding: "9px 14px", fontSize: 13, fontWeight: 600 },
  formHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  iconBtn: { border: "none", background: "#f2f0ea", borderRadius: 6, padding: 6 },
  formLabel: { fontSize: 12, fontWeight: 700, color: "#5c6066", fontFamily: "'Helvetica Neue', Arial, sans-serif", marginBottom: 5 },
  input: { width: "100%", border: "1px solid #e4e2dc", borderRadius: 8, padding: "9px 11px", fontSize: 14, fontFamily: "'Helvetica Neue', Arial, sans-serif", outline: "none", color: "#2f3437", background: "#fff" },
  catPick: { border: "1.5px solid", borderRadius: 8, padding: "7px 12px", fontSize: 12.5, fontWeight: 600, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  connectPickerBtn: { display: "flex", alignItems: "center", gap: 6, background: "#f2f0ea", border: "none", borderRadius: 8, padding: "8px 12px", fontSize: 13, color: "#2f3437", fontWeight: 600, fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  connectList: { marginTop: 8, maxHeight: 220, overflowY: "auto", display: "flex", flexDirection: "column", gap: 6 },
  connectPickItem: { display: "flex", border: "1px solid", borderRadius: 8, padding: "8px 10px", fontSize: 13, fontFamily: "'Helvetica Neue', Arial, sans-serif", color: "#2f3437" },
  formActions: { display: "flex", gap: 10, marginTop: 20, padding: "12px 0", fontFamily: "'Helvetica Neue', Arial, sans-serif", position: "sticky", bottom: 0, background: "#faf9f6", borderTop: "1px solid #eceae4" },
  saveBtn: { flex: 1, background: "#2f6f5e", color: "#fff", border: "none", borderRadius: 8, padding: "11px 14px", fontSize: 14, fontWeight: 700 },
  cancelBtn: { background: "#fff", color: "#5c6066", border: "1px solid #e4e2dc", borderRadius: 8, padding: "11px 14px", fontSize: 14, fontWeight: 600 },
  toast: { position: "fixed", bottom: 20, left: "50%", transform: "translateX(-50%)", background: "#2f3437", color: "#fff", padding: "9px 16px", borderRadius: 20, fontSize: 13, fontFamily: "'Helvetica Neue', Arial, sans-serif" },

  /* ---- auth bar (new) ---- */
  authBar: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", padding: "0 0 14px", fontFamily: "'Helvetica Neue', Arial, sans-serif" },
  authForm: { display: "flex", gap: 8, flex: 1, minWidth: 220 },
  authInput: { flex: 1, border: "1px solid #e4e2dc", borderRadius: 8, padding: "8px 11px", fontSize: 13, fontFamily: "'Helvetica Neue', Arial, sans-serif", outline: "none" },
  authBtn: { background: "#2f6f5e", color: "#fff", border: "none", borderRadius: 8, padding: "8px 14px", fontSize: 13, fontWeight: 600, whiteSpace: "nowrap" },
  authStatus: { fontSize: 12.5, color: "#5c6066", display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  authSignOut: { background: "transparent", border: "none", color: "#a8632a", fontWeight: 600, fontSize: 12.5, padding: 0 },
  authPending: { background: "#fbf1e6", color: "#a8632a", borderRadius: 8, padding: "8px 12px", fontSize: 12.5 },
};
